version: '3.7'

services:

  admin:
    image: ${ETH_NODE_IMAGE_NAME}
    container_name: admin
    working_dir: /root
    volumes:
      - ./network:/root/network
      - ./genesis.json:/root/network/genesis.json
      - ./provision.sh:/root/provision.sh
    networks:
      - local
  
  node1:
    image: ${ETH_NODE_IMAGE_NAME}
    container_name: node1
    volumes:
      - ./network/node1:/root/data
    networks:
      - local

  node2:
    image: ${ETH_NODE_IMAGE_NAME}
    container_name: node2
    volumes:
      - ./network/node2:/root/data
    networks:
      - local
  
  bootnode:
    image: ${ETH_NODE_IMAGE_NAME}
    container_name: bootnode
    volumes:
      - ./network/bootnode:/root/bootnode
    networks:
      - local

networks:
  local:
    name: ${NETWORK_NAME}