version: '3.7'

services:

  admin:
    image: ${ETH_ADMIN_IMAGE_NAME}
    container_name: admin
    working_dir: /root
    ports:
      - 30303:30303
    volumes:
      - ./tmp:/root/admin
    networks:
      - local
  
  node1:
    image: ${ETH_NODE_IMAGE_NAME}
    container_name: node1
    volumes:
      - ./tmp/node1:/root/keystore
    networks:
      - local

  node2:
    image: ${ETH_NODE_IMAGE_NAME}
    container_name: node2
    volumes:
      - ./tmp/node2:/root/keystore
    networks:
      - local

networks:
  local:
    name: ${NETWORK_NAME}